version: '3'

services:
  web:
    environment:
      - ENCRYPTION_KEY=mySecretKey

    build:
      context: .
      args:
        JAR_FILE: target/figma-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    ports:
      - '8080:8080'